site_name: My Docs
site_url: https://gaoxingxs.github.io
site_description: ''
site_author: gaoxingxs
edit_uri: tree/main/docs

# Page tree
nav:
  - 首页: index.md
  - Python:
    - 基础笔记:
      - 0.1 &nbsp; 基础1: python/基础笔记/基础1.md
      - 基础2: python/基础笔记/基础2.md
    - django:
      - 初始django: python/django/初识django.md
      - admin系统: python/django/自带admin管理系统的使用.md
      - 在django中发送邮件: python/django/在django中发送邮件.md
  - JavaScript:
    - Vue:
      - 开发中遇到的问题: javascript/vue/开发中遇到的问题.md
    - React:
      - 入门笔记: javascript/react/入门笔记.md
  

theme:
  name: material
  # custom_dir: build/overrides
  language: zh
  features:
    - announce.dismiss
    # - content.action.edit # 是否显示编辑此页
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # - header.autohide # 顶部header下滑时自动隐藏
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.tabs # 横向导航
    # - navigation.tabs.sticky # 横向导航在页面滚动时是否固定
    # - navigation.sections  #次级目录在侧边栏中平铺
    - navigation.top # 返回顶部的按钮 在上滑时出现
    # - navigation.footer
    - navigation.tracking
    # - navigation.expand # 打开Tab时左侧目录全部展开
    - search.highlight  # 搜索出的文章关键词加入高亮
    # - search.share #搜索分享按钮
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/theme-light-dark
        name: 深色模式
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/theme-light-dark
        name: 浅色模式
  font:
    text: Noto Sans SC
    code: Fira Code

extra:
  generator: false  #删除页脚显示“使用 MkDocs 材料制造”
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      baselevel: 2
  - admonition  # 提示块
  - footnotes  # 脚注
  - meta  # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret  # 下划线上标
  - pymdownx.tilde  # 删除线下标
  - pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details  # 提示块可折叠
  - pymdownx.inlinehilite  # 行内代码高亮
  - pymdownx.mark  # 文本高亮
  - pymdownx.smartsymbols  # 符号转换
  - pymdownx.superfences  # 代码嵌套在列表里
  - pymdownx.highlight:
      anchor_linenums: true
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc:  # 锚点
      permalink: true
#  - pymdownx.arithmatex  # 数学公式
  - pymdownx.betterem:  # 对加粗和斜体更好的检测
      smart_enable: all
#  - pymdownx.emoji:  # 表情
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
#  - pymdownx.magiclink  # 自动识别超链接
  - pymdownx.tasklist:  # 复选框checklist
      custom_checkbox: true

plugins:
  - search:
      lang:
          - en
          - ja
      separator: '[\s\-\.]'
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: none
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      auto_caption: false
      caption_position: bottom